providers:
  openrouter:
    url: "https://openrouter.ai/api/v1"
    token: ""
  deepinfra:
    url: "https://api.deepinfra.com/v1"
    token: ""

llms:
  olmocr:
    provider: "deepinfra"
    model: "allenai/olmOCR-2-7B-1025"
  gemini3:
    provider: "openrouter"
    model: "google/gemini-3-flash-preview"
  gemini3pro:
    provider: "openrouter"
    model: "google/gemini-3.1-pro-preview"
  gemini2fl:
    provider: "openrouter"
    model: "google/gemini-2.5-flash-lite"
  gemini2:
    provider: "openrouter"
    model: "google/gemini-2.5-flash"
  dsgen:
    provider: "openrouter"
    model: "google/gemini-2.5-flash"
  qwen3:
    provider: "openrouter"
    model: "qwen/qwen3-235b-a22b-2507"
  qwen3t:
    provider: "openrouter"
    model: "qwen/qwen3-235b-a22b-thinking-2507"
  sonnet:
    provider: "openrouter"
    model: "anthropic/claude-sonnet-4.6"
  oss:
    provider: "openrouter"
    model: "openai/gpt-oss-120b"
  test-llm:
    provider: "openrouter"
    model: "google/gemini-2.5-flash"
  emb:
    type: emb
    provider: "openrouter"
    model: "openai/text-embedding-3-small"
  test-embeddings:
    type: emb
    provider: "openrouter"
    model: "openai/text-embedding-3-small"

s3:
  key_id: "admin"
  access_key: "admin"
  bucket: "main"
  url: "http://localhost:8333"

n4j:
  conn: "bolt://neo4j:12345678@localhost:7687"
  url: "bolt://localhost:7687"
  username: "neo4j"
  password: "12345678"

redis:
  conn: "redis://localhost:6379"
